version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.48.0/conftest_0.48.0_Linux_x86_64.tar.gz
      - tar xzf conftest.tar.gz -C /usr/local/bin
  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/
      - echo "Running OPA/Conftest checks..."
      - conftest test terraform/
      - echo "Building SageMaker pipeline definition..."
      - python pipeline/sagemaker_pipeline.py
artifacts:
  files:
    - pipeline/sagemaker_pipeline.json
