version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/
      - echo "Running integration tests..."
      - pytest integration_tests/
artifacts:
  files:
    - "**/*"
